WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 368-418-919
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:17:09] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:17:09] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 54, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 99, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:17:09] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:18:17] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:18:17] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:18:30] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:18:30] "GET /backend/saved_images/erar-0-1_002_0000280_00044_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2024 15:18:30] "GET /backend/saved_images/erar-0-1_002_0000280_00044_t.jpg HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/sandra/Desktop/ocr_application_react/backend/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 368-418-919
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 810-366-311
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:37:22] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:37:22] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 99, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:37:22] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:38:43] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:38:43] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 99, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:38:43] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:45:18] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:45:19] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 99, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:45:19] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:54:28] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:54:28] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 99, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:54:28] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:56:56] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:56:56] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 99, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 09:56:56] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/sandra/Desktop/ocr_application_react/backend/database_connection.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 810-366-311
INFO:werkzeug: * Detected change in '/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 810-366-311
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:03:33] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:03:33] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:03:49] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:03:49] "GET /backend/saved_images/erar-0-1_002_0000280_00005_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:04:49] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:04:49] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 83, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:04:49] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 810-366-311
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:07:39] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:07:39] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 91, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:07:39] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:08:14] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:08:14] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 91, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:08:14] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:12:36] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:12:36] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 91, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:12:36] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:21:54] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:21:54] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 91, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:21:54] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:26:03] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:26:03] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 91, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:26:03] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:36:13] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:36:13] "OPTIONS /process HTTP/1.1" 200 -
ERROR:root:An error occurred during OCR processing
Traceback (most recent call last):
  File "/home/sandra/Desktop/ocr_application_react/backend/app.py", line 53, in process_image_endpoint
    process_image(image_path, output_folder)
  File "/home/sandra/Desktop/ocr_application_react/backend/ocr_processing.py", line 91, in process_image
    ocr_text = pytesseract.image_to_string(image, config=ocr_config)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 277, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 197, in save
    image, extension = prepare(image)
  File "/home/sandra/.local/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 174, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:36:13] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:37:55] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:37:55] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:38:12] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:38:12] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:40:20] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:40:20] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:40:36] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:40:36] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:41:27] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:41:27] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:41:44] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:41:44] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:42:45] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:42:45] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:42:58] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:42:58] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:46:49] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:46:49] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:47:03] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:47:03] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:08] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:08] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:23] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:23] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:26] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:26] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:43] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:53:43] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:55:02] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:55:02] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:55:30] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:55:30] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:59:28] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:59:28] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:59:28] "[31m[1mGET /upload HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:59:42] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 10:59:42] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:01:15] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:01:19] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:01:19] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:02:36] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:02:36] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:03:54] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:03:54] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:05:06] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:05:06] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:05:42] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 810-366-311
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:06:28] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:06:28] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:06:43] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:06:43] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:10:52] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:10:52] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:11:08] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:11:08] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:13:39] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:13:39] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:13:54] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:13:54] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:20:01] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:20:01] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:20:19] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:20:19] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:23:04] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:23:04] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:23:20] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:23:20] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:24:32] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:24:32] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:24:46] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:24:46] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:25:11] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:25:11] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:25:28] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:25:28] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:27:18] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:27:18] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:27:30] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:27:30] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 810-366-311
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:27:50] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:27:50] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:28:06] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:28:06] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:28:44] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:28:44] "OPTIONS /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:29:02] "POST /process HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2024 11:29:02] "GET /backend/saved_images/erar-0-1_002_0000280_00002_t.jpg HTTP/1.1" 200 -
